Repository EraMorgett4/Sesac_5_perror, pull requests merged in 2025-06, with the labels that each got.

#4 Update log.md [test request]
  log.md
Labels: 샘플입니다

#19 Feature/byungju/fr-001,fr-002
  .gitignore
  backend/auth.py
  backend/database.py
  backend/main.py
  backend/models.py
  backend/requirements.txt
  backend/schemas.py
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.js
  frontend/src/components/Navbar.js
  frontend/src/contexts/AuthContext.js
  frontend/src/index.js
  frontend/src/pages/Dashboard.js
  frontend/src/pages/Login.js
  frontend/src/pages/Register.js
  frontend/src/pages/RiskMap.js
  frontend/src/pages/RouteSearch.js
  frontend/src/styles/App.css
  frontend/src/styles/Auth.css
  frontend/src/styles/Dashboard.css
  frontend/src/styles/Navbar.css
  frontend/src/styles/RiskMap.css
  frontend/src/styles/RouteSearch.css
  frontend/src/styles/index.css
  log.md
Labels: 기능 개발

#21 Feature/byungju/fr-008
  backend/FR-008/.gitkeep
  backend/FR-008/rag.ipynb
  backend/FR-008/싱크홀.txt
  log.md
Labels: 기능 개발

#22 [Add] 기능 추가
  backend/FR-005/FR-005(ver1).ipynb
  backend/FR-006/FR-006(ver1).ipynb
  log.md
Labels: 기능 개발

#25 [Docs] Update README.md content
  README.md
Labels: 문서작업

#31 [Add]기능 추가
  backend/FR-010/FR-010(ver1).ipynb
  log.md
Labels: 기능 개발

#36 Chore/hsw/anything
  backend/azure_ml_service.py
  backend/data_preprocessing/test.py
  backend/location_analyzer.py
  backend/main.py
  frontend/public/favicon.ico
  frontend/public/images/logo.png
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/Navbar.js
  frontend/src/pages/AzureMltest.js
  frontend/src/pages/NotFound.js
  frontend/src/pages/RiskMap.js
  frontend/src/styles/App.css
  frontend/src/styles/AzureMltest.css
  frontend/src/styles/Dashboard.css
  frontend/src/styles/Navbar.css
  frontend/src/styles/NotFound.css
  frontend/src/styles/ReportChatbot.css
  frontend/src/styles/RiskMap.css
  frontend/src/styles/RouteSearch.css
  log.md
Labels: enhancement
